spring:
  config:
    activate:
      on-profile: deploy

  datasource:
    url: jdbc:mysql://10.8.54.127:3306/dailypaper?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: confluence
    password: smlj@123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  #data:
    #redis:  # Redis
      #host: 10.8.54.127
      #port: 6391
      #username: root
      #password: smlj@123456

logging:
  file:
    name: /data/deploy/dailyPaper/logs/dailyPaper.log