# 同一路径下，配置文件优先级： properties > yml > yaml
# 多环境配置：https://www.bilibili.com/video/BV14z4y1N7pg?p=44&vd_source=5c9f5bd891aee351c325bcf632b5550f 12:48

# web服务器启动端口
server:
  port: 8089

spring:
  profiles: # 测试、开发、部署环境切换
    active: dev

  thymeleaf:
    check-template-location: false

  datasource:
    hikari:
      # springboot运行时偶先报错：Possibly consider using a shorter maxLifetime value
      # https://blog.csdn.net/xgw1010/article/details/113604080
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false

mybatis:
  # resources目录下xml的mapper路径
  mapper-locations: classpath:xmlMapper/*Mapper.xml

  # entity实体类的路径，用于xml文件中的别名，一般是resultType
  # type-aliases-package: com.smlj.dailypaper.entity.po.
