---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3407/dailypaper?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://10.8.13.152:3407/dailypaper?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
---
spring:
  config:
    activate:
      on-profile: deploy

  datasource:
    url: jdbc:mysql://10.8.13.152:3407/dailypaper?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
---

# 同一路径下，配置文件优先级： properties > yml > yaml
server:
  port: 8089

spring:
  profiles: # 测试、开发、部署环境切换
    active: dev

mybatis:
  # resources目录下xml的mapper路径
  mapper-locations: classpath:xmlMapper/*Mapper.xml

  # entity实体类的路径，用于xml文件中的别名，一般是resultType
  type-aliases-package: com.smlj.dailypaper.entity
