spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3407/dailypaper?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #data:
    #redis:  # Redis
      #host: localhost
      #port: 6391
      #username: root
      #password: root

logging:
  file:
    name: F:\Projects\SMLJ\svn\DailyPaper\backend\.logs\out.log.txt