
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:mysql://10.8.54.127:3306/dailypaper?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

cors:
  allowedOrigin:
    -"http://10.8.54.127:5175",
    -"http://10.8.54.127:5176"