# 同一路径下，配置文件优先级： properties > yml > yaml
# 多环境配置：https://www.bilibili.com/video/BV14z4y1N7pg?p=44&vd_source=5c9f5bd891aee351c325bcf632b5550f 12:48

# web服务器启动端口
server:
  port: 8089
  servlet:
    context-path: /

  shutdown: graceful # 优雅停机 关闭容器后默认等待30秒继续执行没处理完的任务 避免数据不一致
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 2500
      min-spare: 500
    # 最大吞吐量不限制
    max-swallow-size: -1
    max-http-form-post-size: -1
    max-connections: 6500
    accept-count: 1000
    # 链接建立超时时间
    connection-timeout: 12000

spring:
  profiles: # 测试、开发、部署环境切换
    active: dev

  datasource: # https://github.com/alibaba/druid/blob/master/druid-spring-boot-3-starter/src/test/resources/application-multi-datasource.properties
    # https://github.com/alibaba/druid/tree/master/druid-spring-boot-3-starter
    type: com.alibaba.druid.pool.DruidDataSource

  jpa: # https://www.zhangbj.com/p/1411.html https://blog.csdn.net/zhaolinfenggg/article/details/135706459
    show-sql: true # 显示sql
    hibernate: # 自动生成表结构
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    check-template-location: false

#  data:
#    # Redis
#    redis:
#      database: 0 # 数据库索引 默认0
#      timeout: 3S # 超时时间:秒

logging:
  level: # https://blog.csdn.net/oYinHeZhiGuang/article/details/120761368
    # 基本类型绑定
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 枚举类型绑定
    org.hibernate.metamodel.model.convert.internal.NamedEnumValueConverter: trace
    web: DEBUG

mybatis:
  # resources目录下xml的mapper路径
  mapper-locations:
    - classpath:xmlMapper/*.xml
    - classpath:xmlMapper/common/*.xml
    - classpath:xmlMapper/common/createTable/*.xml
    - classpath:xmlMapper/table_3rd/jtmenhu/*.xml
  # 配置 MyBatis 配置文件路径
  config-location: classpath:mybatis-config.xml

  # entity实体类的路径，用于xml文件中的别名，一般是resultType
  # type-aliases-package: com.smlj.dailypaper.table*.entity
