server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://10.8.13.152:3407/dailypaper?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver