spring:
  config:
    activate:
      on-profile: dev

  datasource:
    dynamic:
      primary: dailypaper #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      lazy: true
      datasource:
        dailypaper:
          url: jdbc:mysql://localhost:3407/dailypaper?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        jtmenhu:
          url: jdbc:mysql://10.8.54.111:3306/jtmenhu?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
          username: jtmenhu
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver

  #data:
    #redis:  # Redis
      #host: localhost
      #port: 6391
      #username: root
      #password: root

logging:
  file:
    name: F:\Projects\SMLJ\svn\DailyPaper\backend\.logs\out.log.txt